layout_spectrum: 0.5958608
name: Dyson Jewellery  Design
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.6156681
  lightness: 0.5191489
  saturation: 0.5106383
  rhythmicContrast: 0.8802719
  brandColors:
    - '#150910'
    - '#F4F0EA'
    - '#6F6D71'
typography_spectrum: 0.2156021
