layout_spectrum: 0.5958608
typography_spectrum: 0.2156021
color:
  lightness: 0.2957961
  brandStrength: 0.6156681
  saturation: 0.7857678
  rhythmicContrast: 0.8802719
  brandColors:
    - '#879CAB'
    - '#040101'
    - '#7F6E5C'
    - '#E0D8BD'
name: Dyson Jewellery  Design
